spring.application.name=orchestrate

spring.jackson.deserialization.fail-on-unknown-properties=true
spring.mvc.problemdetails.enabled=false

spring.datasource.url=jdbc:h2:mem:orchestrate;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=

spring.flyway.enabled=true

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.directory=logs
server.tomcat.accesslog.prefix=access
server.tomcat.accesslog.suffix=.log
server.tomcat.accesslog.pattern=%t %{X-Trace-Id}o %a "%r" %s %b %Dms